# Generated by Django 4.1.4 on 2022-12-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_text_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
