# Generated by Django 4.1.4 on 2022-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_anonymoususer_alter_chat_user1_alter_chat_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='ip',
            field=models.CharField(default='', max_length=32),
        ),
    ]
