# Generated by Django 4.1.4 on 2022-12-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_anonymoususer_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
