# Generated by Django 4.1.4 on 2022-12-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_anonymoususer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.anonymoususer'),
        ),
    ]
