# Generated by Django 4.1.4 on 2022-12-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='active',
        ),
    ]
