# Generated by Django 4.1.4 on 2022-12-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_chat_disconnected'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user1_typeing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2_typeing',
            field=models.BooleanField(default=False),
        ),
    ]
